### ISSUE TITLE
Need Extraction also 

### ISSUE THREAD

**Issue by vipin2079** [grahamlyons/SQL-Server-Backup-and-Zip#1]
I am looking code is working perfect  even I dis zip file password protected also.now I need to restore particular db but fist i need to unzip the file.

**Comment by grahamlyons** [comment]
Hey @vipin2079, you just need to unzip the file and follow the normal restore procedure for the database.

This code is super old and not something I use or support. Feel free to use it however you like but I won't be adding anything new.

**Comment by vipin2079** [comment]
Grahm,

I need  help from you regarding  zip the file.Currently we are running the
SQL Server 2017 on Linux  and  with your utility.Backup successful but  not
successful in rar.

Could you help me to zip the file in Linux.

/**
 * Author:
 * IT Department SCA
 * Date:
 * 2016-01-20
 * Synopsis:
 * SQL script to backup a database and then add the backup file to a rar
archive.
 * Requires the rar command line utility (or other command line archive
program).
 */
GO
-- Set the name of the database.
DECLARE @dbname NVARCHAR(1024)
SET @dbname = 'Tortilla'
-- Set the name of the archive backup directory.
DECLARE @bakdir VARCHAR(300)
SET @bakdir = '/disk3/backup/'
-- Set the name of the database backup directory.
DECLARE @dbbakdir VARCHAR(300)
SET @dbbakdir = '/tmp/' + @dbname
-- Create the name of the backup file from the database name and the
current date.
DECLARE @bakname VARCHAR(300)
SET @bakname = @dbname + '_backup_' + REPLACE(CONVERT(VARCHAR(20),
GETDATE(), 112) + CONVERT(VARCHAR(20), GETDATE(), 108),':','')
-- Set the name of the backup file.
DECLARE @filename VARCHAR(300)
SET @filename = @dbbakdir + '/' + @bakname+'.bak'
-- Create the directories if necessary.
EXECUTE master.dbo.xp_create_subdir @dbbakdir
EXECUTE master.dbo.xp_create_subdir @bakdir
-- Backup the database.
BACKUP DATABASE @dbname
TO  DISK = @filename
WITH NOFORMAT, NOINIT,  NAME = @bakname, SKIP, REWIND, NOUNLOAD,  STATS = 10

-- Turn on the 'xp_cmdshell' function.
EXEC sp_configure 'show advanced options', 1
RECONFIGURE
EXEC sp_configure 'xp_cmdshell', 1
RECONFIGURE
-- Build the command line string to add the file to the ZIP archive.
DECLARE @cmd VARCHAR(300)
SET @cmd ='rar -a -ep -hpsc@r$cS "' + @bakdir + @bakname + '.rar" "' +
@filename + '"'
-- Execute the command.
EXEC xp_cmdshell @cmd
-- Turn off the 'xp_cmdshell' function.
EXEC sp_configure 'xp_cmdshell', 0
RECONFIGURE
EXEC sp_configure 'show advanced options', 0
RECONFIGURE
GO

**Comment by grahamlyons** [comment]
Hi @vipin2079,

With very little to go on in terms of what's actually going wrong I'd take a wild stab in the dark and guess that either `rar` isn't installed (`apt-get install -y rar`) or isn't available on the `PATH` that SQL Server is using.

I wrote my SQL script in 2010 and I haven't used SQL Server since then so I don't think I'm best placed to advise you on this.

The code you've pasted into your issue was written by IT Department SCA so I'd suggest you ask them for help.

As I said two years ago, this code is super old and isn't something I use anymore. You're free to use it but I don't support it.
